# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  vmImage: 'macos-10.15'
  demands:
  - xcode
  - Xamarin.iOS
  - MSBuild
  - Xamarin.Android
  - JDK

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'

- bash: |
   echo "Setting SDK version to 6_12_9"
   SYMLINK=6_12_9
   MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
   echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
   echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
   echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
   sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_9
   echo "Mono current"
   cd /Library/Frameworks/Mono.framework/Versions
   ls -l
   echo "Xamarin-iOS  current"
   cd  /Library/Frameworks/Xamarin.iOS.framework/Versions
   ls -l
   echo "Xamarin-Android  current"
   cd  /Library/Frameworks/Xamarin.Android.framework/Versions
   ls -l
   echo "Xamarin-Mac  current"
   cd /Library/Frameworks/Xamarin.Mac.framework/Versions
   ls -l
   xcrun simctl erase all
  displayName: 'Set SDK Versions (Mono, Xamarin-iOS, Xamarin-Android, Xamarin-Mac)'


- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: MSBuild@1
  displayName: "Restore Microcharts.Droid packages"
  inputs:
    msbuildArguments: /t:restore
    solution: 'Sources/Microcharts.Droid/Microcharts.Droid.csproj'
    configuration: 'Release'

# - task: NuGetCommand@2
#   inputs:
#     command: 'pack'
#     packagesToPack: 'NuGet/Microcharts.Forms.nuspec'
#     packDestination: '$(Build.ArtifactStagingDirectory)'
#     configuration: 'Release'
#     versioningScheme: 'off'
#     basePath: '/'
#     buildProperties: 'version=$(GitVersion.MajorMinorPatch)-$(GitVersion.EscapedBranchName)-$(GitVersion.BuildMetaDataPadded)'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/Microcharts.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'



# - task: XamarinAndroid@1
#   displayName: 'Build Microchart.Droid packages'
#   inputs:
#     projectFile: '**/Microcharts.Droid.csproj'
#     configuration: 'Release'
#     createAppPackage: false
#     jdkOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     msbuildVersionOption: '15.0'




